version: '3'
services:
  # Postgres database
  postgres:
    image: 'postgres:12'
    environment:
      - POSTGRES_PASSWORD=postgres_password

  # Redis
  redis:
    image: 'redis:latest'

  # server, named as api for nginx config
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password

  # client
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true

  # worker
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app

  # nginx for routing
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3070:80'
    # This command may not be needed
    #command: ["nginx", "-g", "daemon off;"]
